CREATE INDEX "role_company_idx" ON "role" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "subscription_company_idx" ON "subscription" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "customer_company_idx" ON "customer" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "model_company_idx" ON "model" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "project_company_idx" ON "project" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "vendor_company_idx" ON "vendor" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "bom_company_idx" ON "bom" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "checklist_template_company_idx" ON "checklist_template" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "ap_billing_company_idx" ON "ap_billing" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "ar_invoice_company_idx" ON "ar_invoice" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "attendance_company_idx" ON "attendance" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "bank_statement_company_idx" ON "bank_statement" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "cheque_company_idx" ON "cheque" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "fixed_asset_company_idx" ON "fixed_asset" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "jv_company_idx" ON "jv" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "payroll_company_idx" ON "payroll" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "pv_company_idx" ON "pv" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "reconcile_company_idx" ON "reconcile" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "rv_company_idx" ON "rv" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "worker_company_idx" ON "worker" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "audit_log_company_idx" ON "audit_log" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "document_company_idx" ON "document" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "land_plot_company_idx" ON "land_plot" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "notification_company_idx" ON "notification" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "sales_unit_company_idx" ON "sales_unit" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "ar_credit_note_company_idx" ON "ar_credit_note" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "bid_comparison_company_idx" ON "bid_comparison" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "inventory_item_company_idx" ON "inventory_item" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "lead_company_idx" ON "lead" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "material_issue_company_idx" ON "material_issue" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "milestone_company_idx" ON "milestone" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "org_unit_company_idx" ON "org_unit" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "petty_cash_txn_company_idx" ON "petty_cash_txn" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "ppa_invoice_company_idx" ON "ppa_invoice" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "retention_ledger_company_idx" ON "retention_ledger" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "rev_rec_company_idx" ON "rev_rec" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "service_ticket_company_idx" ON "service_ticket" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "solar_inverter_company_idx" ON "solar_inverter" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "solar_om_ticket_company_idx" ON "solar_om_ticket" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "solar_permit_step_company_idx" ON "solar_permit_step" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "solar_roi_company_idx" ON "solar_roi" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "solar_warranty_company_idx" ON "solar_warranty" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "stock_transfer_company_idx" ON "stock_transfer" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "timeline_task_company_idx" ON "timeline_task" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "warehouse_company_idx" ON "warehouse" USING btree ("company_id");--> statement-breakpoint
CREATE INDEX "wip_company_idx" ON "wip" USING btree ("company_id");--> statement-breakpoint
ALTER TABLE "doc_numbering" ADD CONSTRAINT "doc_numbering_company_type_uq" UNIQUE("company_id","type");