CREATE INDEX "project_node_project_idx" ON "project_node" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "project_node_parent_idx" ON "project_node" USING btree ("parent_id");--> statement-breakpoint
CREATE INDEX "boq_doc_project_idx" ON "boq_doc" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "boq_doc_project_status_idx" ON "boq_doc" USING btree ("project_id","status");--> statement-breakpoint
CREATE INDEX "boq_doc_approved_by_idx" ON "boq_doc" USING btree ("approved_by");--> statement-breakpoint
CREATE INDEX "boq_group_boq_idx" ON "boq_group" USING btree ("boq_id");--> statement-breakpoint
CREATE INDEX "boq_item_group_idx" ON "boq_item" USING btree ("group_id");--> statement-breakpoint
CREATE INDEX "boq_version_history_doc_idx" ON "boq_version_history" USING btree ("doc_id");--> statement-breakpoint
CREATE INDEX "cbs_budget_group_idx" ON "cbs_budget" USING btree ("group_id");--> statement-breakpoint
CREATE INDEX "defect_report_gr_idx" ON "defect_report" USING btree ("gr_id");--> statement-breakpoint
CREATE INDEX "gr_item_gr_idx" ON "gr_item" USING btree ("gr_id");--> statement-breakpoint
CREATE INDEX "gr_item_boq_item_idx" ON "gr_item" USING btree ("boq_item_id");--> statement-breakpoint
CREATE INDEX "gr_po_idx" ON "gr" USING btree ("po_id");--> statement-breakpoint
CREATE INDEX "gr_wo_idx" ON "gr" USING btree ("wo_id");--> statement-breakpoint
CREATE INDEX "po_pr_idx" ON "po" USING btree ("pr_id");--> statement-breakpoint
CREATE INDEX "po_pr_status_idx" ON "po" USING btree ("pr_id","status");--> statement-breakpoint
CREATE INDEX "pr_item_pr_idx" ON "pr_item" USING btree ("pr_id");--> statement-breakpoint
CREATE INDEX "pr_item_boq_item_idx" ON "pr_item" USING btree ("boq_item_id");--> statement-breakpoint
CREATE INDEX "pr_project_idx" ON "pr" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "pr_project_status_idx" ON "pr" USING btree ("project_id","status");--> statement-breakpoint
CREATE INDEX "pr_vendor_idx" ON "pr" USING btree ("vendor_id");--> statement-breakpoint
CREATE INDEX "pr_requester_idx" ON "pr" USING btree ("requester_id");--> statement-breakpoint
CREATE INDEX "variation_order_po_idx" ON "variation_order" USING btree ("po_id");--> statement-breakpoint
CREATE INDEX "wo_pr_idx" ON "wo" USING btree ("pr_id");--> statement-breakpoint
CREATE INDEX "wo_pr_status_idx" ON "wo" USING btree ("pr_id","status");--> statement-breakpoint
CREATE INDEX "wo_contract_idx" ON "wo" USING btree ("contract_id");--> statement-breakpoint
CREATE INDEX "acceptance_period_idx" ON "acceptance" USING btree ("period_id");--> statement-breakpoint
CREATE INDEX "defect_acceptance_idx" ON "defect" USING btree ("acceptance_id");--> statement-breakpoint
CREATE INDEX "subcon_contract_project_idx" ON "subcon_contract" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "work_period_contract_status_idx" ON "work_period" USING btree ("contract_id","status");--> statement-breakpoint
CREATE INDEX "pm_asset_contract_idx" ON "pm_asset" USING btree ("contract_id");--> statement-breakpoint
CREATE INDEX "pm_contract_project_idx" ON "pm_contract" USING btree ("project_id");--> statement-breakpoint
CREATE INDEX "pm_workorder_asset_idx" ON "pm_workorder" USING btree ("asset_id");--> statement-breakpoint
CREATE INDEX "ap_billing_po_idx" ON "ap_billing" USING btree ("po_id");--> statement-breakpoint
CREATE INDEX "ap_billing_gr_idx" ON "ap_billing" USING btree ("gr_id");