import {
  mkdirSync,
  readdirSync,
  readFileSync,
  rmSync,
  writeFileSync,
} from "node:fs";
import { dirname, join, relative } from "node:path";
import type { DiffResult } from "./compare";

// tests/visual/lib/report.ts — readable diff report for the visual gate
// (Gate G5 — "รายงาน diff อ่านได้", P0-QA-04). All artifacts live under
// tests/visual/.results/ (gitignored — never under reference/).
//
// Worker-safe by design: Playwright runs specs across parallel workers, so each
// test records its own part file (recordScreen). globalTeardown then reads every
// part and consolidates one deterministic report — no cross-worker races.

export const RESULTS_DIR = join(__dirname, "..", ".results");
const PARTS_DIR = join(RESULTS_DIR, "parts");
const DIFF_DIR = join(RESULTS_DIR, "diff");

export interface ScreenResult extends DiffResult {
  // route id / screen key from tests/visual/reference-index.md, or a self-check id.
  screen: string;
  kind: "self-check" | "capture";
}

function ratioPct(r: number): string {
  return `${(r * 100).toFixed(4)}%`;
}

function safeName(s: string): string {
  return s.replace(/[^a-z0-9._-]+/gi, "_");
}

/** Remove stale artifacts so a run starts clean (called from globalSetup). */
export function resetResults(): void {
  rmSync(RESULTS_DIR, { recursive: true, force: true });
  mkdirSync(PARTS_DIR, { recursive: true });
}

/** Persist one screen's diff PNG; returns its path relative to RESULTS_DIR. */
function writeDiffImage(screen: string, r: DiffResult): string | null {
  if (!r.diffPngBase64) return null;
  const file = join(DIFF_DIR, `${safeName(screen)}.png`);
  mkdirSync(dirname(file), { recursive: true });
  writeFileSync(file, Buffer.from(r.diffPngBase64, "base64"));
  return relative(RESULTS_DIR, file);
}

/** Record one screen result from any worker (writes the diff PNG + a part file). */
export function recordScreen(result: ScreenResult): void {
  mkdirSync(PARTS_DIR, { recursive: true });
  const diffPath = writeDiffImage(result.screen, result);
  const { diffPngBase64, ...rest } = result;
  const part = { ...rest, diffPath };
  const unique = `${safeName(result.screen)}.${process.pid}.${process.hrtime.bigint()}`;
  writeFileSync(join(PARTS_DIR, `${unique}.json`), JSON.stringify(part));
}

interface Part extends Omit<ScreenResult, "diffPngBase64"> {
  diffPath: string | null;
}

/** Consolidate all part files into one JSON + Markdown report (globalTeardown). */
export function aggregate(): { jsonPath: string; mdPath: string } {
  mkdirSync(RESULTS_DIR, { recursive: true });
  let parts: Part[] = [];
  try {
    parts = readdirSync(PARTS_DIR)
      .filter((f) => f.endsWith(".json"))
      .map((f) => JSON.parse(readFileSync(join(PARTS_DIR, f), "utf8")) as Part);
  } catch {
    parts = [];
  }
  parts.sort((a, b) =>
    (a.kind + a.screen).localeCompare(b.kind + b.screen)
  );

  const summary = {
    total: parts.length,
    pass: parts.filter((r) => r.verdict === "PASS").length,
    fail: parts.filter((r) => r.verdict === "FAIL").length,
    generatedBy: "P0-QA-04 visual gate harness",
  };

  const jsonPath = join(RESULTS_DIR, "visual-report.json");
  writeFileSync(jsonPath, JSON.stringify({ summary, results: parts }, null, 2));

  const rows = parts
    .map((r) => {
      const ref = r.refPath.split("/reference/")[1] ?? r.refPath;
      return `| ${r.screen} | ${r.kind} | \`${ref}\` | ${r.candLabel} | ${r.refDims.w}x${r.refDims.h} | ${r.candDims.w}x${r.candDims.h} | ${r.diffPixels} | ${ratioPct(r.diffRatio)} | **${r.verdict}** | ${r.note}${r.diffPath ? ` · diff: \`${r.diffPath}\`` : ""} |`;
    })
    .join("\n");

  const md = `# Visual Gate diff report (G5 · P0-QA-04)

> Generated by the visual gate harness · PLAN.md §0 + §9 · zone \`qa\`
> Reference pack is read-only ground truth — this report NEVER modifies it.

## Summary

- Total: **${summary.total}** · PASS: **${summary.pass}** · FAIL: **${summary.fail}**

## Per-screen

| screen | kind | reference | candidate | ref dims | cand dims | diff px | diff ratio | verdict | note |
|---|---|---|---|---|---|---|---|---|---|
${rows || "| _(no screens compared — app not built yet; real captures pending apps/web)_ |||||||||"}

## How to read

- **diff ratio** = differing pixels ÷ total pixels. Verdict FAIL when it exceeds
  \`VISUAL_MAX_DIFF_PIXEL_RATIO\` (default 0 = strict, per skill \`visual-gate\`).
- A **dimension mismatch** auto-FAILs (layout change — PLAN.md §0).
- Diff PNGs highlight differing pixels in red under \`.results/diff/\`.
`;

  const mdPath = join(RESULTS_DIR, "visual-report.md");
  writeFileSync(mdPath, md);
  return { jsonPath, mdPath };
}
